### PR TITLE
Ensure topic existence after creating new topic

### LINKED ISSUE #403: Create a topic can lead to a UnknownTopicOrPartitionException when the broker is slow
hi team akhq
I am currently using akhq 0.15 version with standalone installation ... when I create a topic on UI akhq, the following error appears

Sep 19 02:12:22 monkaf-84 java[347293]: 2020-09-19 02:12:22,389 #033[39mDEBUG#033[0;39m #033[35m-thread-83#033[0;39m #033[36morg.akhq.utils.Logger     #033[0;39m 29 ms -> Create Topics
Sep 19 02:12:22 monkaf-84 java[347293]: 2020-09-19 02:12:22,392 #033[1;31mERROR#033[0;39m #033[35mGroup-1-10#033[0;39m #033[36mo.a.c.ErrorController     #033[0;39m Error for Describe Topic Config {}
Sep 19 02:12:22 monkaf-84 java[347293]: java.lang.RuntimeException: Error for Describe Topic Config {}
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.utils.Logger.call(Logger.java:31)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.modules.AbstractKafkaWrapper.describeConfigs(AbstractKafkaWrapper.java:290)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$$exec13.invokeInternal(Unknown Source)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:60)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$Intercepted.describeConfigs(Unknown Source)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.repositories.ConfigRepository.find(ConfigRepository.java:48)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.repositories.ConfigRepository.update(ConfigRepository.java:72)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.repositories.ConfigRepository.updateTopic(ConfigRepository.java:66)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.repositories.TopicRepository.create(TopicRepository.java:157)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.controllers.TopicController.createApi(TopicController.java:228)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at org.akhq.controllers.$TopicControllerDefinition$$exec5.invokeInternal(Unknown Source)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2995)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:286)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$16(RoutingInBoundHandler.java:1474)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:68)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onSuccess(MaybeToFlowable.java:70)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onSuccess(RxInstrumentedMaybeObserver.java:82)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.maybe.MaybeDoOnEvent$DoOnEventMaybeObserver.onSuccess(MaybeDoOnEvent.java:86)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onSuccess(RxInstrumentedMaybeObserver.java:82)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:68)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:501)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:665)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:68)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:117)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onSuccess(MaybeToFlowable.java:70)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onSuccess(RxInstrumentedMaybeObserver.java:82)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onSuccess(MaybeCreate.java:73)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at java.base/java.util.Optional.ifPresent(Optional.java:183)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.security.session.SessionAuthenticationFetcher.lambda$fetchAuthentication$0(SessionAuthenticationFetcher.java:53)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Maybe.subscribe(Maybe.java:4290)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Maybe.subscribe(Maybe.java:4290)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:68)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:236)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:54)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Maybe.subscribe(Maybe.java:4290)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Maybe.subscribe(Maybe.java:4290)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.maybe.MaybeDoOnEvent.subscribeActual(MaybeDoOnEvent.java:39)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Maybe.subscribe(Maybe.java:4290)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Maybe.subscribe(Maybe.java:4290)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14868)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:153)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onNext(FlowableSwitchMap.java:129)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:68)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.core.async.publisher.CompletableFuturePublisher$CompletableFutureSubscription.lambda$request$0(CompletableFuturePublisher.java:87)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.core.async.publisher.CompletableFuturePublisher$CompletableFutureSubscription.request(CompletableFuturePublisher.java:81)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.request(FlowableSwitchMap.java:162)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.request(FlowableSwitchMap.java:162)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredSetOnce(SubscriptionHelper.java:202)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.subscribers.StrictSubscriber.onSubscribe(StrictSubscriber.java:87)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:54)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:54)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onSubscribe(FlowableSwitchMap.java:93)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:54)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onSubscribe(FlowableSwitchMap.java:93)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:54)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.core.async.publisher.CompletableFuturePublisher.subscribe(CompletableFuturePublisher.java:48)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14868)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14918)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.Flowable.subscribe(Flowable.java:14865)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:144)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Sep 19 02:12:22 monkaf-84 java[347293]: #011at java.base/java.lang.Thread.run(Thread.java:834)
Sep 19 02:12:22 monkaf-84 java[347293]: Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
Sep 19 02:12:22 monkaf-84 java[347293]: 2020-09-19 02:12:22,395 #033[31mWARN #033[0;39m #033[35mGroup-1-10#033[0;39m #033[36morg.akhq.log.access       #033[0;39m [Date: 2020-09-19T02:12:22.356543+07:00] [Duration: 39 ms] [Url: POST
/api/kafka-cluster-ssl/topic] [Status: 500] [Ip: 1912] [Length: 172.16.254.79] [Port: 8080]

Get help from the team ... tks

### PR DESCRIPTION
**Pull request by tobiade**
- Fixes #403
- We add a retry to ensure a topic exists after a `createTopics` command is issued.
- We need this due to delays that could be involved in topic reation. From the Kafka docs:

> It may take several seconds after CreateTopicsResult returns success for all the brokers to become aware that the topics have been created. During this time, listTopics() and describeTopics(Collection) may not return information about the new topics.

### CODE REVIEW

File: src/test/java/org/akhq/repositories/TopicRepositoryTest.java [hunk 1]
```diff
@@ -167,6 +170,20 @@ public void partition() throws ExecutionException, InterruptedException {
         assertEquals(3, topicRepository.findByName(KafkaTestCluster.CLUSTER_ID, KafkaTestCluster.TOPIC_COMPACTED).getPartitions().size());
     }
 
+    @Test
+    public void shouldThrowIfTopicDoesNotExist() {
+        final String topicName = "unknownTopic";
+        assertThrows(UnknownTopicOrPartitionException.class, () -> topicRepository.checkIfTopicExists(KafkaTestCluster.CLUSTER_ID, topicName));
```
Comment (tobiade) [inline src/test/java/org/akhq/repositories/TopicRepositoryTest.java:176]: I'd like to verify that kafkaWrapper is indeed invoked a number of times here, but unsure as to how to inject a mocked instance of KafkaWrapperTest/AbstractKafkaWrapper into TopicRepository. 

If you have any ideas, please let me know!

File: src/test/resources/application.yml [hunk 2]
```diff
@@ -153,3 +153,6 @@ akhq:
           groups:
             - operator
 
+  retry:
```
Comment (tobiade) [inline src/test/resources/application.yml:156]: Please let me know if this is okay to add - I've added this so we can control the delay when running unit tests, but I'm aslo wary we're exposing this property to users.

**Comment by tobiade** [comment]
Hmm I see the build is failing due to this error:

```java
   java.lang.NullPointerException
          at org.akhq.AbstractTest.getProperties(AbstractTest.java:86)
          at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.resolveTestProperties(MicronautJunit5Extension.java:145)
          at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.resolveTestProperties(MicronautJunit5Extension.java:47)
          at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:206)
          at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:61)
```
That's a bit odd - seems to build fine on my machine

File: src/test/resources/application.yml (hunk 2 above)
Comment (tchiotludo) [reply src/test/resources/application.yml:156]: Exposing the options is fine I think but please puyt in `akhq.topic.retry` and add it to `application.example.yml`

File: src/test/java/org/akhq/repositories/TopicRepositoryTest.java (hunk 1 above)
Comment (tchiotludo) [reply src/test/java/org/akhq/repositories/TopicRepositoryTest.java:176]: Really hard to add a test on the retry, it will be flakky since it depend on kafka server. 
Maybe we can trust the micronaut implementation and don't add a test here

**Review by tchiotludo — COMMENTED** [review]
The error is gone after retry, must be a github action temp failure ... 
Just few remark and it's ok for me

File: src/test/java/org/akhq/repositories/TopicRepositoryTest.java (hunk 1 above)
Comment (tobiade) [reply src/test/java/org/akhq/repositories/TopicRepositoryTest.java:176]: Cool, sounds okay to me - will remove

**Comment by tobiade** [comment]
Thanks @tchiotludo - updated
